name: taph
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  flutter_barcode_scanner: ^2.0.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  carousel_slider: ^4.2.1
  image_picker: ^0.8.6+4
  select_form_field: ^2.2.0
  multiselect_formfield: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/